language: android

branches:
    excludes:
        - gh-pages

notifications:
    email:
        - isoblue@layton.in

android:
    components:
        - build-tools-19.1

jdk:
    - oraclejdk7
    - openjdk7

script: mvn clean package
